server.port=8081

spring.application.name=GIU
server.servlet.context-path=/GIU

# Muestra los errores detallados del DispatcherServlet
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# Muestra los fallos espec�ficos en los convertidores de mensajes HTTP
logging.level.org.springframework.http.converter=DEBUG
# Obliga a Tomcat a registrar excepciones de bajo nivel en el ciclo de vida del Request
#logging.level.org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]=DEBUG

logging.config=file:/applications/config/EAF/CO_Claro_IntCus_EAF_Domain_PR/config/GIU-BFF/Log4jgiu.properties
# Forzar a usar el StandardServletMultipartResolver de Servlet 3.0+
