# application.properties
logging.config=file:/applications/config/GIU-BFF/Log4jgiu.properties

# Ruta multiplataforma (Funciona en Windows, Linux, Unix y macOS)
system.data.base.logger.file.config=/applications/config/GIU-BFF/Log4jgiu.properties


Log4jGIU-campeones.properties
system.spring.application.name=GIU
system.server.servlet.context-path=/GIU
system.app.ttl.nonce.seconds=1800

# ==========================================
# CONFIGURACIÓN DE ACCESO A BD (PARAMETROS)
# ==========================================

# 1. Producción / QA (WebLogic)
system.db.jndi.name=jdbc/GIUDataSource

# 1. Desarrollo Local (Sin WebLogic)
system.db.local.driver=oracle.jdbc.OracleDriver
system.db.local.url=jdbc:oracle:thin:@//desktop-v2po0qp:1521/xepdb1
system.db.local.user=DEV_PRACTICAS
system.db.local.password=Dev123

# 2. Consulta de propiedades 
system.db.query.parametros=SELECT tp.CODIGO AS CLAVE, tp.VALOR AS VALOR FROM DEV_PRACTICAS.TBL_PARAMETROS tp WHERE tp.COD_APP = ?

# ==========================================
# CONFIGURACIÓN DEL HAZELCAST
# ==========================================
system.app.nodos.cache=localhost:5740
system.hazelcast.default.port:8002
system.hazelcast.cluster.name=GIU-bff-cluster
system.hazelcast.map.session.cache=GIU-session-cache
system.hazelcast.token.map.name=GIU-token-cache
system.hazelcast.token.key=GIU_BEARER_TOKEN

# ==========================================
# CONFIGURACIÓN DE TIMEOUT DE LOS SERVICIOS
# ==========================================

# Tiempo máximo para establecer la conexión con el servicio destino
system.app.connect.timeout.services.milliseconds=10000

# Tiempo máximo para obtener una conexión disponible del pool
system.app.connection.request.timeout.services.milliseconds=5000

# Tiempo máximo de espera por respuesta/datos del servicio
system.app.socket.timeout.services.milliseconds=30000


# ============================================
# PROXIES
# ============================================
system.claro.proxies.ser-general-api=http://172.24.42.253:8100/WSSerGeneral
system.claro.proxies.endpoint.registro.auditoria=http://172.24.42.253:8100/WSSerGeneral/logs/guardar?Accion=i
system.claro.proxies.giu-api=http://operoperexteap.gtm.claro.com.co:8082/WSSalesChannelredemption-web
system.claro.proxies.odi-api=http://100.123.246.44:8080/EXP_WSReStInf1InvokenV1.0


# ============================================
# configuracion para generar el token desde el bff
# ============================================
system.claro.auth.url=http://operoperexteap.gtm.claro.com.co:8082/WSSalesChannelredemption-web/auth/token?nombreUsuario=10306845322&password=registroNuevo
system.claro.proxies.successFactor=http://172.24.160.148:8080/EXP_WSSalesChannelredemptionV1.0/PS_WSSalesChannelRedemptionV1.0_RS/GetUserInfo

# ============================================
# Configuración SFTP para el modulo de PQR
# ============================================
system.sftp.pqr.host=172.24.42.143
system.sftp.pqr.user=ecm7949b
system.sftp.pqr.pass=M1ddl3w@r3
system.sftp.pqr.path=/applogs/CO_Claro_IntCus_EAF_Domain_PR/GIUDocPQR

# ==========================================
# SFTP - Cargue Manual de Puntos
# ==========================================
system.app.cargue.manual.puntos.ip.Sftp=172.24.42.143
system.app.cargue.manual.puntos.usuario.Sftp=ecm7949b
system.app.cargue.manual.puntos.contrasena.Sftp=M1ddl3w@r3
system.app.cargue.manual.puntos.path.Sftp=/applogs/CO_Claro_IntCus_EAF_Domain_PR/WSGIU/CarguePuntos

