status = INFO
name = GIUBFF
monitorInterval = 30

property.nameApp = GIU-bff

# DECLARAR APPENDERS
appenders = rolling, stdout

# Appender Consola
appender.stdout.type = Console
appender.stdout.name = STDOUT
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = [%d{dd/MM/yyyy HH:mm:ss.SSS}][%-5level][REQUEST-ID=%X{REQUEST-ID}][TX-ID=%X{TX-ID}][USER-ID=%X{USER-ID}][%-20C{1}][%-20M]%m\r\n

# Appender Archivo Rolling (Sin C: para compatibilidad Windows/Linux)
appender.rolling.type = RollingFile
appender.rolling.name = RollingFileAppender
appender.rolling.fileName = /applogs/CO_Claro_IntCus_EAF_Domain_PR/GIU-bff/GIU-bff.log
appender.rolling.filePattern = /applogs/CO_Claro_IntCus_EAF_Domain_PR/GIU-bff/GIU-bff.log.%d{yyyy-MM-dd}
appender.rolling.append = true
appender.rolling.immediateFlush = true

appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = [%d{dd/MM/yyyy HH:mm:ss.SSS}][%-5level][REQUEST-ID=%X{REQUEST-ID}][TX-ID=%X{TX-ID}][USER-ID=%X{USER-ID}][%-20C{1}][%-20M]%m\r\n
appender.rolling.layout.charset = UTF-8

appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true

# ROOT LOGGER
rootLogger.level = INFO
rootLogger.appenderRefs = rollingRef, stdoutRef
rootLogger.appenderRef.rollingRef.ref = RollingFileAppender
rootLogger.appenderRef.stdoutRef.ref = STDOUT

# LOGGER DE TU APLICACIÓN
logger.giu.name = co.com.claro
logger.giu.level = INFO
logger.giu.appenderRefs = rollingRef, stdoutRef
logger.giu.appenderRef.rollingRef.ref = RollingFileAppender
logger.giu.appenderRef.stdoutRef.ref = STDOUT
logger.giu.additivity = false