/**
 * Permisos del sistema GIU.
 * Los permisos son genéricos y representan capacidades administrables.
 */
export const PERMISSIONS = {
  // Aplicaciones
  APLICACIONES_VER: 'APLICACIONES_VER',
  APLICACIONES_CREAR: 'APLICACIONES_CREAR',
  APLICACIONES_EDITAR: 'APLICACIONES_EDITAR',
  APLICACIONES_GESTIONAR_ESTADO: 'APLICACIONES_GESTIONAR_ESTADO',
  // Usuarios
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_GESTIONAR_ESTADO: 'USUARIOS_GESTIONAR_ESTADO',
  USUARIOS_ASIGNAR_ROL: 'USUARIOS_ASIGNAR_ROL',
  // Roles
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  ROLES_ASIGNAR_PERMISOS: 'ROLES_ASIGNAR_PERMISOS',
  // Permisos/Recursos
  PERMISOS_VER: 'PERMISOS_VER',
  PERMISOS_CREAR: 'PERMISOS_CREAR',
  PERMISOS_EDITAR: 'PERMISOS_EDITAR',
  // Administradores
  ADMINISTRADORES_VER: 'ADMINISTRADORES_VER',
  ADMINISTRADORES_GESTIONAR: 'ADMINISTRADORES_GESTIONAR',
  // Auditoría
  AUDITORIA_VER: 'AUDITORIA_VER',
  // Reportes
  REPORTES_VER: 'REPORTES_VER',
} as const;

/**
 * Todos los permisos como array (para asignación mock).
 */
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
